using System.Text;
using Content.Shared._DEN.Language;
using Content.Shared._DEN.Language.EntitySystems;
using Content.Shared._DEN.Requirements.Managers;
using Content.Shared.Preferences;
using Robust.Client.AutoGenerated;
using Robust.Client.Player;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;
using Range = Robust.Client.UserInterface.Controls.Range;

namespace Content.Client._DEN.Lobby.UI.Languages;

[GenerateTypedNameReferences]
public sealed partial class LanguageSelector : BoxContainer
{
    [Dependency] private IPrototypeManager _prototypeManager = default!;
    [Dependency] private IPlayerManager _player = default!;
    [Dependency] private IPlayerRequirementManager _requirements = default!;

    public event Action<HumanoidCharacterProfile?>? OnPreferenceUpdated;

    private HumanoidCharacterProfile? _profile;
    private LanguageEntryPrototype _entryProto;
    private LanguagePrototype? _langProto;
    private List<ProtoId<LanguageFluencyPrototype>> _langFluencies;
    private LanguagePreference _langPreference;
    private int _points;
    private int _maxPoints;

    /// <summary>
    /// A selector which is a group of: Language name with a tooltip of the language description. A fluency slider and
    /// text display. An Option Box for selecting speaking, translating, or neither, for a language. And a checkbox for
    /// if this language should be marked as your primary.
    /// </summary>
    /// <param name="profile">The current HumanoidCharacterProfile, used for getting preferences.</param>
    /// <param name="entryProto">The LanguageEntryPrototype that this selector represents.</param>
    /// <param name="langFluencies">Prototype versions of the language fluencies.</param>
    /// <param name="points"></param>
    /// <param name="maxPoints"></param>
    public LanguageSelector(HumanoidCharacterProfile? profile, LanguageEntryPrototype entryProto, List<ProtoId<LanguageFluencyPrototype>> langFluencies, int? points, int? maxPoints)
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);
        _entryProto = entryProto;
        _langFluencies = langFluencies;
        _profile = profile;
        _points = points ?? 0;
        _maxPoints = maxPoints ?? SharedLanguageSystem.LanguageSelectionPoints;
        LanguagePreference? preference = null;
        if (_profile?.LanguagePreferences.TryGetValue(entryProto.ID, out var prefVal) is true)
            preference = prefVal;
        _langPreference = preference ?? new LanguagePreference(SharedLanguageSystem.MinimumFluency, SpokenState.None, false);

        Initialize();
    }

    private void Initialize()
    {
        var context = GetContext();
        if (SharedPlayerRequirementManager.ShouldHide(context, _entryProto.Requirements))
        {
            Visible = false;
            return;
        }

        // Disable all the buttons if we don't meet the requirements.
        if (!SharedPlayerRequirementManager.CheckRequirements(context, _entryProto.Requirements))
        {
            SpeaksOptionButton.Disabled = true;
            FluencySlider.Disabled = true;
            PrimaryButton.Disabled = true;
        }

        _langProto = _prototypeManager.Index(_entryProto.LanguageProto);
        LanguageNameLabel.ToolTip = _langProto.LocalizedDescription;
        LanguageNameLabel.MouseFilter = MouseFilterMode.Pass;

        SpeaksOptionButton.AddItem(Loc.GetString("language-selector-none-text"), 0);
        SpeaksOptionButton.AddItem(Loc.GetString("language-selector-spoken-text"), 1);
        SpeaksOptionButton.AddItem(Loc.GetString("language-selector-translator-text"), 2);
        SpeaksOptionButton.Disabled = SpeaksOptionButton.Disabled || _langPreference.Primary;
        SpeaksOptionButton.SelectId((int)_langPreference.Speaks);
        SpeaksOptionButton.OnItemSelected += args =>
        {
            SpeaksOptionButton.SelectId(args.Id);
            LanguageSpeechPreferenceUpdated();
        };

        if (!SharedPlayerRequirementManager.CheckRequirements(context, _entryProto.SpeakingRequirements))
            SpeaksOptionButton.SetItemDisabled(1, true);

        if (!_entryProto.CanHaveTranslator)
            SpeaksOptionButton.SetItemDisabled(2, true);

        PrimaryButton.Pressed = _langPreference.Primary;
        PrimaryButton.OnPressed += _ => LanguagePrimaryPreferenceUpdated();

        FluencySlider.MaxValue = _langFluencies.Count - 1;
        FluencySlider.LockMaxValue = FluencySlider.MaxValue;
        FluencySlider.LockMinValue = 0;
        var curVal = _langFluencies.IndexOf(_langPreference.Fluency);
        FluencySlider.Value = curVal == -1 ? 0 : curVal;
        FluencySlider.OnValueChanged += FluencySliderChanged;
        FluencySlider.OnReleased += _ => LanguageFluencyPreferenceUpdated();
        FluencySlider.Disabled = FluencySlider.Disabled || _langPreference.Primary;

        if (_prototypeManager.TryIndex(_langPreference.Fluency, out var fluency))
            LanguageFluencyLabel.Text = Loc.GetString(fluency.Name);

        var availablePoints = _maxPoints - _points;
        LimitFluencySlider(availablePoints);
        LimitSpeechOptions(availablePoints);
        LimitPrimaryButton(availablePoints);
        UpdateNameLabel();
    }

    private PlayerRequirementContext GetContext()
    {
        var session = _player.LocalSession;
        if (session == null)
            return new();

        var context = _requirements.GetPlayerContext(session);
        return context;
    }

    // Locks the fluency slider to only move within ranges that we have enough points to spend.
    private void LimitFluencySlider(int availablePoints)
    {
        switch (availablePoints)
        {
            case 0:
                if (_langPreference.Fluency == SharedLanguageSystem.MinimumFluency)
                    FluencySlider.LockMaxValue = 1;
                else if (_langPreference.Fluency != SharedLanguageSystem.MaximumFluency)
                    FluencySlider.LockMaxValue = _langFluencies.Count - 2;
                break;
            case 1:
                if (_langPreference.Fluency == SharedLanguageSystem.MinimumFluency)
                    FluencySlider.LockMaxValue = _langFluencies.Count - 2;
                break;
        }

        if (PrimaryButton.Pressed)
            FluencySlider.LockMinValue = _langFluencies.Count - 1;
    }

    // Lock the speech options based on how many points we have to spend.
    private void LimitSpeechOptions(int availablePoints)
    {
        switch (availablePoints)
        {
            case 0:
                // Can't spend a point to speak if we're not already on speaks.
                if (_langPreference.Speaks == SpokenState.None)
                {
                    SpeaksOptionButton.SetItemDisabled(1, true);
                    SpeaksOptionButton.SetItemDisabled(2, true);
                }
                break;
            case 1:
                // Can only turn on speech at 1 point if we're already fluent.
                if (_langPreference.Speaks != SpokenState.Speaks && _langPreference.Fluency != SharedLanguageSystem.MaximumFluency)
                    SpeaksOptionButton.SetItemDisabled(1, true);
                break;
            case 2:
                if (_langPreference.Fluency == SharedLanguageSystem.MinimumFluency)
                    SpeaksOptionButton.SetItemDisabled(1, true);
                break;
        }
    }

    // Lock the primary button if we don't have enough points to promote a language to primary.
    private void LimitPrimaryButton(int availablePoints)
    {
        switch (availablePoints)
        {
            case 0:
                if (_langPreference.Speaks == SpokenState.None ||
                    (_langPreference.Fluency != SharedLanguageSystem.MaximumFluency && _langPreference.Speaks == SpokenState.Translator))
                    PrimaryButton.Disabled = true;
                break;
            case 1:
                if (_langPreference.Fluency != SharedLanguageSystem.MaximumFluency)
                    PrimaryButton.Disabled = true;
                break;
            case 2:
                if (_langPreference.Fluency == SharedLanguageSystem.MinimumFluency)
                    PrimaryButton.Disabled = true;
                break;
        }
    }

    private void FluencySliderChanged(Range range)
    {
        var fluency = (int)range.Value;

        if (_prototypeManager.TryIndex(_langFluencies[fluency], out var fluencyProto))
        {
            _langPreference.Fluency = fluencyProto;
            UpdateNameLabel();
            LanguageFluencyLabel.Text = Loc.GetString(fluencyProto.Name);
        }
    }

    // Build a profile with the speech preference selected.
    private void LanguageSpeechPreferenceUpdated()
    {
        var spokenState = (SpokenState)SpeaksOptionButton.SelectedId;
        _profile = _profile?.WithLanguageSpeechPreference(_entryProto.ID, spokenState);

        OnPreferenceUpdated?.Invoke(_profile);
    }

    // Build a profile with the new fluency selected.
    private void LanguageFluencyPreferenceUpdated()
    {
        var fluency = _langFluencies[(int)FluencySlider.Value];
        _profile = _profile?.WithLanguageFluency(_entryProto.ID, fluency);

        OnPreferenceUpdated?.Invoke(_profile);
    }

    // Build a profile with the new primary preference selected.
    private void LanguagePrimaryPreferenceUpdated()
    {
        var primary = PrimaryButton.Pressed;
        _profile = _profile?.WithLanguagePrimary(_entryProto.ID, primary);

        OnPreferenceUpdated?.Invoke(_profile);
    }

    private void UpdateNameLabel()
    {
        LanguageNameLabel.Text = GetNameLabelText();
    }

    private string GetNameLabelText()
    {
        var langName = _langProto?.LocalizedName ?? "";
        var costText = Loc.GetString("language-selector-name-label-cost-text",
            ("cost", _langPreference.GetPointCost()));

        return Loc.GetString("language-selector-name-label-text",
            ("language", langName),
            ("cost", costText));
    }
}
