using Content.Shared.Humanoid;
using Content.Shared.Humanoid.Prototypes;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;

namespace Content.Client._DEN.Lobby.UI.Controls;

/// <summary>
///     A control that allows for selecting a skin color based on a given skin coloration strategy.
/// </summary>
[GenerateTypedNameReferences]
public sealed partial class SkinColorSliders : BoxContainer
{
    [Dependency] private IPrototypeManager _protoMan = default!;

    /// <summary>
    ///     Event fired when the current color of the sliders are changed.
    /// </summary>
    public event Action<Color>? OnColorChanged;

    /// <summary>
    ///     The current color associated with these sliders.
    /// </summary>
    public Color Color => GetCurrentColor();

    /// <summary>
    ///     The skin coloration prototype associated with these sliders.
    /// </summary>
    private SkinColorationPrototype? _skinColor = null;

    /// <summary>
    ///     The currently-active color selection strategy.
    /// </summary>
    private ISkinColorationStrategy? _currentStrategy = null;

    private static readonly LocId DefaultToggleButtonText = "humanoid-profile-editor-skin-alt-strategy-toggle-button";

    public SkinColorSliders()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        ColorSliders.OnColorChanged += _ => { OnSliderValueChanged(); };
        LinearSlider.OnValueChanged += _ => { OnSliderValueChanged(); };
        ToggleAltStrategyButton.OnToggled += args => { OnAltStrategyToggled(); };

        ColorSliders.SelectorType = ColorSelectorSliders.ColorSelectorType.Hsv;
    }

    /// <summary>
    ///     Sets the skin color selection strategy from a species prototype.
    /// </summary>
    /// <param name="protoId">The species prototype to use.</param>
    public void SetSkinColoration(ProtoId<SpeciesPrototype> protoId)
    {
        if (!_protoMan.Resolve(protoId, out var species))
            return;

        SetSkinColoration(species.SkinColoration);
    }

    /// <summary>
    ///     Sets the skin color selection strategy from a skin coloration prototype.
    /// </summary>
    /// <param name="protoId">The skin color prototype to use.</param>
    public void SetSkinColoration(ProtoId<SkinColorationPrototype> protoId)
    {
        if (!_protoMan.Resolve(protoId, out var skinColor))
            return;

        _skinColor = skinColor;

        // Set the visible strategy to match the new skin coloration prototype.
        var currentColor = GetCurrentColor();
        UpdateBestStrategyForColor(currentColor);

        // Ensure the newly-visible strategy has the correct color.
        SetSliderColor(currentColor);
    }

    /// <summary>
    ///     Sets the current skin color of this slider.
    /// </summary>
    /// <remarks>
    ///     This should be set when the profile is updated, such as switching or importing profiles.
    ///     This updates the color selector to match the best applicable strategy.
    /// </remarks>
    /// <param name="color">The color to set the slider to.</param>
    public void SetSkinColor(Color color)
    {
        if (_skinColor is null)
            return;

        // Update the visible strategy according to what best fits this new color.
        UpdateBestStrategyForColor(color);

        // Update the visible sliders with the color.
        SetSliderColor(color);
    }

    /// <summary>
    ///     Set the color value of the slider controls themselves based on the current strategy.
    /// </summary>
    /// <param name="color">The color to set the slider values to.</param>
    private void SetSliderColor(Color color)
    {
        if (_currentStrategy is null)
            return;

        switch (_currentStrategy.InputType)
        {
            case SkinColorationStrategyInput.Unary:
                var sliderValue = _currentStrategy.ToUnary(color);
                LinearSlider.SetValueWithoutEvent(sliderValue);
                break;

            case SkinColorationStrategyInput.Color:
                ColorSliders.Color = color;
                break;
        }
    }

    private void SetAltStrategyActive(bool active)
    {
        if (_skinColor is null)
            return;

        if (_skinColor.AltStrategy is null)
            active = false;

        _currentStrategy = active ? _skinColor.AltStrategy : _skinColor.Strategy;
        ToggleAltStrategyButton.Pressed = active;

        var buttonLocale = _skinColor.ToggleButtonText ?? DefaultToggleButtonText;
        var buttonText = Loc.GetString(buttonLocale);
        ToggleAltStrategyButton.Text = buttonText;

        UpdateSliderVisibility();
    }

    /// <summary>
    ///     Notify subscribers that the color has changed when the sliders are changed.
    /// </summary>
    private void OnSliderValueChanged()
    {
        if (_skinColor is null)
            return;

        var color = GetCurrentColor();
        OnColorChanged?.Invoke(color);
    }

    /// <summary>
    ///     Toggle the current strategy between primary and alternate when the toggle button is pressed.
    /// </summary>
    private void OnAltStrategyToggled()
    {
        if (_skinColor is null)
            return;

        var currentColor = GetCurrentColor();

        // Can't enable alt strategies if this skin coloration doesn't have one.
        if (_skinColor.AltStrategy == null)
        {
            _currentStrategy = _skinColor.Strategy;
            SetAltStrategyActive(false);
            SetSliderColor(currentColor);
            OnSliderValueChanged();
            return;
        }

        // Update the alt strategy.
        var enabled = ToggleAltStrategyButton.Pressed;
        SetAltStrategyActive(enabled);
        SetSliderColor(currentColor);
        OnSliderValueChanged();
    }

    /// <summary>
    ///     Sets the currently-active strategy based on the closest match to a given color.
    /// </summary>
    /// <param name="color">The color used to update the active strategy.</param>
    private void UpdateBestStrategyForColor(Color color)
    {
        if (_skinColor is null)
            return;

        var useAlt = _skinColor.AltStrategy != null && PreferAltStrategyForColor(color);
        SetAltStrategyActive(useAlt);
    }

    /// <summary>
    ///     Updates which slider elements are visible based on the current strategy.
    /// </summary>
    private void UpdateSliderVisibility()
    {
        if (_skinColor is null)
            return;

        ToggleAltStrategyButton.Visible = _skinColor.AltStrategy is not null;

        if (_currentStrategy is null)
            return;

        switch (_currentStrategy.InputType)
        {
            case SkinColorationStrategyInput.Unary:
                LinearSliderBox.Visible = true;
                ColorSliderBox.Visible = false;
                break;

            case SkinColorationStrategyInput.Color:
                LinearSliderBox.Visible = false;
                ColorSliderBox.Visible = true;
                break;
        }
    }

    /// <summary>
    ///     Gets the currently-selected slider color for this control.
    /// </summary>
    /// <returns>The current color for the active sliders.</returns>
    /// <exception cref="ArgumentOutOfRangeException">Thrown if the current strategy's input type is not handled.</exception>
    private Color GetCurrentColor()
    {
        var color = Color.White;

        if (_skinColor is null || _currentStrategy is null)
            return color;

        color = _currentStrategy.InputType switch
        {
            SkinColorationStrategyInput.Unary => GetUnaryColor(_currentStrategy),
            SkinColorationStrategyInput.Color => GetRgbColor(_currentStrategy),
            _ => throw new ArgumentOutOfRangeException(nameof(_currentStrategy.InputType)),
        };

        return color;
    }

    /// <summary>
    ///     Get the current slider color for a unary color strategy.
    /// </summary>
    /// <param name="strategy">The skin color strategy.</param>
    /// <returns>The current slider color.</returns>
    private Color GetUnaryColor(ISkinColorationStrategy strategy)
    {
        var sliderValue = LinearSlider.Value;
        var color = strategy.FromUnary(sliderValue);

        return color;
    }

    /// <summary>
    ///     Get the current slider color for an RGB color strategy.
    /// </summary>
    /// <param name="strategy">The skin color strategy.</param>
    /// <returns>The current slider color.</returns>
    private Color GetRgbColor(ISkinColorationStrategy strategy)
    {
        var sliderValue = ColorSliders.Color;
        var color = strategy.ClosestSkinColor(sliderValue);

        return color;
    }

    /// <summary>
    ///     Get whether or not the alt skin color strategy fits a given color better than the primary strategy.
    /// </summary>
    /// <param name="color">The input color.</param>
    /// <returns>Whether we should use the alt strategy instead of the primary one.</returns>
    private bool PreferAltStrategyForColor(Color color)
    {
        if (_skinColor is null || _skinColor.AltStrategy is null)
            return false;

        var primary = _skinColor.Strategy;
        var alt = _skinColor.AltStrategy;

        // If the color is valid for one strategy but not the other,
        // we should use the valid strategy.
        var primaryValid = primary.VerifySkinColor(color, out var _);
        var altValid = alt.VerifySkinColor(color, out var _);

        if (primaryValid && !altValid)
            return false;

        if (!primaryValid && altValid)
            return true;

        // If the alternate strategy is closer, then we're using it.
        _skinColor.VerifyColor(color, out var altIsCloser);
        return altIsCloser;
    }
}
