using System.Text;
using Content.Shared._DEN.Traits.Prototypes;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;
using Robust.Shared.Utility;

namespace Content.Client._DEN.Lobby.UI.Traits;

[GenerateTypedNameReferences]
public sealed partial class EntityTraitSelector : BoxContainer
{
    public event Action<bool>? PreferenceChanged;

    public int Cost { private set; get; } = 0;
    public bool Preference
    {
        get => SelectorCheckbox.Pressed;
        set => SelectorCheckbox.Pressed = value;
    }

    public ProtoId<EntityTraitPrototype>? PrototypeId { private set; get; } = null;
    private EntityTraitPrototype? _trait = null;

    public EntityTraitSelector(EntityTraitPrototype trait)
    {
        RobustXamlLoader.Load(this);

        SetTrait(trait);
        SelectorCheckbox.OnToggled += args => { PreferenceChanged?.Invoke(args.Pressed); };
        SelectorCheckbox.TooltipSupplier = SupplyTooltip;
    }

    private void SetTrait(EntityTraitPrototype trait)
    {
        Cost = trait.Cost;
        PrototypeId = trait.ID;
        _trait = trait;

        var text = "";

        if (trait.Cost != 0)
            text += $"[{trait.Cost}] ";

        text += Loc.GetString(trait.Name);
        SelectorCheckbox.Text = text;
    }

    /// <summary>
    ///     Provide a tooltip to this control if it has a valid trait set.
    ///     This includes the trait's description and its requirement text.
    /// </summary>
    /// <returns>A tooltip with the trait's description, if this control has a trait.</returns>
    private Tooltip? SupplyTooltip(Control sender)
    {
        if (_trait is null)
            return null;

        var tooltip = new Tooltip();
        var tooltipString = ConstructTooltipDescription(_trait);

        if (FormattedMessage.TryFromMarkup(tooltipString, out var msg))
            tooltip.SetMessage(msg);

        return tooltip;
    }

    /// <summary>
    ///     Construct a full tooltip description for a given trait.
    /// </summary>
    /// <param name="trait">The trait to construct a description out of.</param>
    /// <returns>The tooltip text associated with this trait.</returns>
    private static string ConstructTooltipDescription(EntityTraitPrototype trait)
    {
        var tooltipBuilder = new StringBuilder();

        if (trait.Description is not null)
            tooltipBuilder.AppendLine(Loc.GetString(trait.Description.Value));

        if (trait.Requirements.Count > 0)
        {
            tooltipBuilder.AppendLine(); // Empty line
            foreach (var requirement in trait.Requirements)
            {
                var reason = requirement.GetReason();
                if (reason is null)
                    continue;

                tooltipBuilder.AppendLine(reason);
            }
        }

        var tooltipString = tooltipBuilder.ToString();
        var lineBreak = "\n";

        if (tooltipString.EndsWith(lineBreak))
            tooltipString = tooltipString[..^lineBreak.Length];

        return tooltipString;
    }

    public void SetInvalid(bool invalid)
    {
        SelectorCheckbox.Label.FontColorOverride = invalid ? Color.Red : null;
    }
}
