- type: entity
  abstract: true
  id: BaseStationGlimmer
  components:
  - type: GlimmerTracker
    glimmerLevels: 10
    glimmerPerLevel: 100
    startingGlimmerLevelRange: 0, 2
    global: true
    offMapAffectsGlimmer: true
